swagger: "2.0"
info:
  version: "1.0.0"
  title: "Auth API"
basePath: "/v1"
schemes:
  - "https"
consumes:
  - "application/json"
produces:
  - "application/json"
paths:
  /cm/users/auth:
    post:
      summary: "Authenticate user"
      description: "Authenticate user by email address"
      parameters:
        - name: "body"
          in: "body"
          required: true
          schema:
            type: "object"
            properties:
              type:
                type: "string"
                enum: ["EMAIL"]
              value:
                type: "string"
      responses:
        "200":
          description: "OK"
        "400":
          description: "Invalid input"
        "401":
          description: "Unauthorized"